# -*- coding: utf-8 -*-
"""Tarefacriacaodeumabasededadostreinamento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yDknIjPxgT5chHInY4XJsBWXQwNuuTRp
"""

!git clone https://github.com/ultralytics/yolov5.git

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov5

!pip install -r requirements.txt

import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image
import torch

def plot_bounding_box(image_path, label_path, class_names):
    """Plota a imagem com os bounding boxes."""

    # Carrega a imagem
    img = Image.open(image_path)

    # Carrega as anotações do arquivo de rótulos
    with open(label_path, 'r') as f:
        annotations = f.readlines()

    # Cria a figura e os eixos para o plot
    fig, ax = plt.subplots(1)
    ax.imshow(img)

    # Desenha os bounding boxes
    for annotation in annotations:
        # Separa os valores da anotação
        class_id, x_center, y_center, width, height = map(float, annotation.split())

        # Converte as coordenadas normalizadas para pixels
        x_center *= img.width
        y_center *= img.height
        width *= img.width
        height *= img.height

        # Calcula as coordenadas do canto superior esquerdo do bounding box
        x = x_center - width / 2
        y = y_center - height / 2

        # Cria o retângulo do bounding box
       # rect = patches.Rectangle((x, y), width, height, linewidth=2, edgecolor='r', facecolor='none')
        rect = patches.Rectangle((x, y), width, height, linewidth=2, edgecolor='b', facecolor='none')
        # Adiciona o bounding box ao plot
        ax.add_patch(rect)

        # Adiciona o nome da classe ao plot
        class_name = class_names[int(class_id)]
        #ax.text(x, y, class_name, color='w', fontsize=10, backgroundcolor='r')
        ax.text(x, y, class_name, color='w', fontsize=10, backgroundcolor='blue')  # Mude 'blue' para a cor desejada

    # Mostra o plot
    plt.show()

    torch.save(model, 'tarefaCurso.pt')

image_path = '/content/drive/MyDrive/dataset/imagens/train/paisagem16.jpeg'
label_path = '/content/drive/MyDrive/dataset/imagens/imagensescrita/paisagem16.txt'

class_names = ['arvore', 'casa','vaca','estrada','nuvem']

class_names = {
    0: 'arvore',
    1: 'vaca',
    2: 'piscina',
    3: 'casa',
    4: 'estrada',
    5: 'nuvem'  # Adicione mais classes conforme necessário
}

plot_bounding_box(image_path, label_path, class_names)